site_name: Small Bird Site
site_url: https://tishenme.github.io/smallbird-site/
site_author: Tishen
site_description: >-
  Welcome to Shaun's rabbit hole. This site serves as a personal knowledge base for me to record my thoughts and ideas. It is also a place for me to share my knowledge and experience with the world. I hope you find something useful here.

repo_name: tishenme/smallbird-site
repo_url: https://github.com/tishenme/smallbird-site
edit_uri: tree/main/docs/

copyright: Copyright &copy; 2024 ~ now | 🚀 Tishen

theme:
  custom_dir: material/overrides
  favicon: assets/small-bird-icon-128x128.png
  logo: assets/small-bird-icon-128x128.png
  # language: zh
  language: en
  name: material
  features:
    - announce.dismiss
    - content.action.view
    # - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand # expand the side navigation bar by default
    - navigation.footer
    - navigation.indexes # documents can be directly attached to sections, which is particularly useful for providing overview pages
    # - navigation.instant
    - navigation.instant.prefetch # for large file
    - navigation.instant.progress # loading progress bar
    - navigation.path # breadcrumb path on top of page
    # - navigation.prune # only build the visible part of the navigation tree
    # - navigation.sections # navigation - top level will render as sections
    - navigation.tabs
    - navigation.tabs.sticky # tabs stick to the top of the page
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate # toc is merged into the left navigation bar
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code

plugins:
  - tags
  - blog
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  tags:
    Default: default-tag
    Hardware: hardware-tag
    Software: software-tag

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home:
      - "index.md"
      - ABOUT: "./HOME/about.md"
      - SPONSORSHIP: "./HOME/sponsorship.md"
  - Soft:
      - "index.md"
      - ABOUT: "./HOME/about.md"
      - SPONSORSHIP: "./HOME/sponsorship.md"
  - PL:
      - "./notes/vcs/index.md"
  - IDE:
      - "./notes/vcs/index.md"
  - VCS:
      - "./notes/vcs/index.md"
      - Git:
          - Info1: "./notes/vcs/git/index.md"
          - Info2: "./notes/vcs/git/index.md"
          - Info3: "./notes/vcs/git/index.md"
          - Info4: "./notes/vcs/git/index.md"
  - CICD:
      - "index.md"
      - ABOUT: "./HOME/about.md"
      - SPONSORSHIP: "./HOME/sponsorship.md"
  - Cloud:
      - "index.md"
      - Google Cloud: "./HOME/about.md"
      - SPONSORSHIP: "./HOME/sponsorship.md"
